### ISSUE TITLE
Python-*  and *-python named packages are not well recognized

### ISSUE THREAD

**Issue by Cajuteq** [fpgmaas/deptry#410]
**Describe the bug**

Using some package with python-* or *-python in their names, the packages are considered obsolete and their "import" name is considered missing

![image](https://github.com/fpgmaas/deptry/assets/26676532/237953d1-7ae1-4cb9-8ea0-176bd2c0d415)

**To Reproduce**

1. use ffmpeg-python and python-magic in a fastapi project
2. make the install with poetry
3. run deptry .

**Expected behavior**

deptry should recognize python-* and *-python with a warning ; the same way it assumes things on dash and underscores
![image](https://github.com/fpgmaas/deptry/assets/26676532/b2008feb-bc23-4661-9d4e-3a5a736ad5c1)

**System [please complete the following information]:**

-   OS: Windows11 WSL2 Debian
-   Language Version: Python 3.9
-   Poetry version: Poetry 1.2.2

**Additional context**

Not critical at all, probably a "good first issue" tag

**Comment by fpgmaas** [comment]
Hi @Cajuteq! Thanks for raising the issue. At first glance, it seems that these packages are missing a top-level module name. However, given the warnings regarding `pylint` and `pytest`, it seems more likely that you are not running deptry within the virtual environment. This would probably be solved by running either:

```shell
poetry run deptry .
```

or

```shell
poetry shell
deptry .
```

I tested this solution by adding the dependencies to my project and running `deptry` in verbose mode. The results show that the top-level dependencies are indeed present:

```
The project contains the following dependencies:
[...]
Dependency 'python-magic' with top-levels: {'magic'}.
Dependency 'ffmpeg-python' with top-levels: {'ffmpeg'}.
```

Please let me now it this resolves the bug for you as well.

**Comment by Cajuteq** [comment]
I just tried both, and it doesn't seem to do the trick (screen using poetry shell)
![image](https://github.com/fpgmaas/deptry/assets/26676532/51c7d30f-17df-4d8d-beef-b7565bbcb48e)

**Comment by Cajuteq** [comment]
Re-running with -v I got top levels, but those seem to be different from yours, maybe a version issue ?

![image](https://github.com/fpgmaas/deptry/assets/26676532/46897b1c-fa10-4462-973b-b667f752c3b2)

**Comment by fpgmaas** [comment]
Strange. Could you maybe let us know which version of deptry you are using? (`deptry --version`).

Also, since I am not able to reproduce the error, would it be possible to share a minimal `pyproject.toml` that would give this error?

**Comment by fpgmaas** [comment]
Example `pyproject.toml`:

```toml
[tool.poetry]
name = "deptrytest"
version = "0.0.1"
description = "a"
authors = ["Florian Maas <fpgmaas@gmail.com>"]
repository = "https://github.com/fpgmaas/deptry"
documentation = "https://fpgmaas.github.io/deptry/"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
ffmpeg-python = "^0.2.0"
python-magic = "^0.4.27"

[tool.poetry.group.dev.dependencies]
deptry = "^0.11.0"
```

and `foo.py`:

```python
import ffmpeg
import magic
```

Steps:
- place `foo.py` and `pyproject.toml` in same directory
- `poetry install`
- `poetry run deptry .`

Output:

```shell
Scanning 1 file...

Success! No dependency issues found.
```
