### ISSUE TITLE
pre-commit hook requires deptry to be globally installed

### ISSUE THREAD

**Issue by kumekay** [fpgmaas/deptry#414]
**Describe the bug**

We run pre-commit for all changes in a merge request in GitLab CI. `pre-commit` is the only python package-
pre-commit hook requires deptry to be globally installed. 

**To Reproduce**

1. Create `.pre-commit-config.yml` like:

```
repos:
  - repo: https://github.com/fpgmaas/deptry.git
    rev: "0.11.0"
    hooks:
      - id: deptry
```

2. Install the only package `pip install pre-commit`
3. Make some changes in python code and stage changes
4. Run `pre-commit`
5. An error will be returned

```
[INFO] Initializing environment for https://github.com/fpgmaas/deptry.git.
deptry.................................................................................................Failed
- hook id: deptry
- exit code: 1
Executable `deptry` not found
```

**Expected behavior**

Pre-commit installs dependencies by itself. 

**System [please complete the following information]:**

-   OS: e.g. [Debian bullseye]
-   Language Version: [Python 3.10]
-   Poetry version: NA

**Additional context**

**Comment by fpgmaas** [comment]
Hi @kumekay, thanks for raising the issue! `deptry` does not need to be installed globally, but it does need to be installed within the virtual environment of the project. `pre-commit` creates it's own virtual environment, and thus AFAIK the approach proposed in https://github.com/fpgmaas/deptry/pull/415 will not work.

See also the discussion here for more information: https://github.com/fpgmaas/deptry/pull/124#issuecomment-1254726612

**Comment by kumekay** [comment]
@fpgmaas Thank you so much for the explanation (and the great tool). Even though this behavior is mentioned in `important` block in the docs, I was surprised because it's the only pre-commit hook of more than a dozen in our project that requires more than `pre-commit` package.

**Comment by jamesbraza** [comment]
I just hit this today, it surfaces as a semi-cryptic error:

```none
error: Failed to run hook `deptry`
  caused by: Failed to run `deptry .`
  caused by: No such file or directory (os error 2)
```

From https://github.com/osprey-oss/deptry/pull/124#issuecomment-1254726612 by @mkniewallner, a nice workaround is documented:

> While the hook itself would work, in most cases it won't be useful because deptry needs knowledge of all the dependencies that are installed.
> 
> Since pre-commit creates a dedicated virtualenv with no knowledge of the project dependencies, the usefulness of such a hook is limited IMO.
> 
> [pre-commit.com/index.html#system](https://pre-commit.com/index.html#system) may be useful in that regards, since the command could be `poetry run deptry .`, making deptry aware of the already installed dependencies.

Per that, I am using `repo: local` plus `uv run`:

```yaml
- repo: local
  hooks:
    - id: deptry
      # SEE: https://github.com/osprey-oss/deptry/blob/0.25.1/.pre-commit-hooks.yaml
      name: deptry
      description: >-
        deptry is a command line tool to check for issues with dependencies
        in a Python project, such as unused or missing dependencies.
      entry: uv run deptry .
      language: system
      always_run: true
      pass_filenames: false
```

This technique:
- Works if a virtual environment is activated or not
- Works if a virtual environment is present or not (e.g. after a fresh Git clone)
- Removes the dead `deptry` version pin in `rev`, as `deptry` comes from `system` anyways ([link](https://github.com/osprey-oss/deptry/blob/0.25.1/.pre-commit-hooks.yaml#L4-L5))

Note that this setup requires a `uv` project with `deptry` configured as a dependency (either as a regular dependency or a dev dependency). However, that requirement is fine because it's the premise of `deptry` -- a dev setup with listed dependencies be present.
