### ISSUE TITLE
Support for Django

### ISSUE THREAD

**Issue by estahn** [fpgmaas/deptry#467]
**Is your feature request related to a problem? Please describe.**

We use [`aws-xray-sdk`](https://pypi.org/project/aws-xray-sdk/) with our Django app.

`deptry` reports:
```bash
pyproject.toml: DEP002 'aws-xray-sdk' defined as a dependency but not used in the codebase
```

I assume the reason for this is that the module is only referenced as part of the `INSTALLED_APPS` setting:
```python
    INSTALLED_APPS: List[str] = [
        ...
        "aws_xray_sdk.ext.django",
		...
    ]
```

**Describe the solution you would like**

I have seen the following used in other projects:

```toml
[tool.django-stubs]
django_settings_module = "app.settings"
```

This could possibly be adopted:
```toml
[tool.deptry]
django_settings_module = "app.settings"
```
