### ISSUE TITLE
Avoid Cargo as a dependency for using deptry with pre-commit

### ISSUE THREAD

**Issue by nathanjmcdougall** [fpgmaas/deptry#592]
**Is your feature request related to a problem? Please describe.**

As of v0.14.0, building `deptry` requires Cargo to be installed.
Since `pre-commit` builds the pre-commits locally, this means that using `deptry` with pre-commit requires Cargo.

**Describe the solution you would like**

I think the documentation could be updated to explain this fact.

An alternative way to use deptry with pre-commit would be to get it to run locally:

```YAML
-   repo: local
    hooks:
    -   id: deptry
        name: deptry
        entry: deptry .
        additional_dependencies: [deptry==0.14.0]
        language: python
        always_run: true
        pass_filenames: false
```

Perhaps this could be suggested as a recommended workaround, in the documentation.

**Additional context**

See #590.
