### ISSUE TITLE
Dynamic still failing in `pyproject.toml`

### ISSUE THREAD

**Issue by balihb** [fpgmaas/deptry#944]
**Environment**

- **deptry version**: 0.21.0
- **Python version**: 3.12
- **Operating system** (e.g. Ubuntu 22.04, Windows 11): win and linux

**Describe the issue**

Related to #855 now I'm getting with the new version the following error:

```text
    with requirements_file.open() as requirements_file_content:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'r'
```

Same with `deptry .` and `deptry . --requirements-files requirements.txt`.

**Minimal way to reproduce the issue**

**Expected behavior**

**Additional context**

The relevant parts of the config:

```toml
[project]
# ...
requires-python = ">=3.12"
dynamic = ["version", "dependencies", "optional-dependencies"]

# ...

[tool.setuptools.dynamic]
# ...
dependencies = { file = "requirements.txt" }
```
